// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfSlJqOyHBfGk-perJQAKdUYj1XcbT_HM',
    appId: '1:56557221868:web:1ab9e451c0599bd967b2c9',
    messagingSenderId: '56557221868',
    projectId: 'otalk-app',
    authDomain: 'binefa.web.app',
    storageBucket: 'otalk-app.firebasestorage.app',
    measurementId: 'G-QRRS5SPRQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRrUhQbZS5vQtzS7xYybimCokcGFL2uOk',
    appId: '1:56557221868:android:5202bc430a422b0a67b2c9',
    messagingSenderId: '56557221868',
    projectId: 'otalk-app',
    storageBucket: 'otalk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBItsx3proQB7BNtUFLTiMqzRKbuHOkulQ',
    appId: '1:56557221868:ios:ff5b21a6a44d8a5167b2c9',
    messagingSenderId: '56557221868',
    projectId: 'otalk-app',
    storageBucket: 'otalk-app.firebasestorage.app',
    iosBundleId: 'com.otalk.otalkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBItsx3proQB7BNtUFLTiMqzRKbuHOkulQ',
    appId: '1:56557221868:ios:ff5b21a6a44d8a5167b2c9',
    messagingSenderId: '56557221868',
    projectId: 'otalk-app',
    storageBucket: 'otalk-app.firebasestorage.app',
    iosBundleId: 'com.otalk.otalkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfSlJqOyHBfGk-perJQAKdUYj1XcbT_HM',
    appId: '1:56557221868:web:4da05afa3e32192367b2c9',
    messagingSenderId: '56557221868',
    projectId: 'otalk-app',
    authDomain: 'binefa.web.app',
    storageBucket: 'otalk-app.firebasestorage.app',
    measurementId: 'G-NYNG7SCFSB',
  );
}
